public/manifest.json, src/components/CashOutPay/CashOutPay.test.tsx, src/components/Checkout/Checkout.scss, src/components/Checkout/Checkout.tsx, src/components/GetTransactionModal/GetTransactionModal.test.tsx, src/components/GetTransactionModal/GetTransactionModal.tsx, src/components/GetTransactionModal/index.tsx, src/components/Input/Input.tsx, src/components/Order/Order.test.tsx, src/components/Order/Order.tsx, src/components/Pairing/Pairing.tsx, src/components/PairingConfig/PairingConfig.tsx, src/components/Products/Products.tsx, src/components/RefundPay/RefundPay.test.tsx, src/services/cashout.ts, src/services/moto.ts, src/services/purchase.ts, src/services/refund.ts, src/services/transactionFlow.ts
- Add the ability to get a transaction
- Add posRefId to flow messages for successful transactions
- Fix pairing state when canceled before pairing
- Fix broken tests
- Fix the icon size in the application manifest
=> Add the ability to get a transaction

src/components/Checkout/Checkout.tsx, src/components/CreditCardPay/CreditCardPay.tsx, src/components/MotoPay/MotoPay.tsx, src/components/OrderPay/OrderPay.tsx, src/components/Products/Products.tsx, src/services/moto.ts
- fixed Prefix of POS REF ID on a MOTO transaction is cashout
- no error message displayed when trying to initiate a transaction if there's no internet connection
=> implemented error message when no internet 

package-lock.json, package.json, src/components/CustomTextField/index.styles.ts, src/components/PairPage/FlowPanel/index.styles.ts, src/components/PairPage/PairForm/index.styles.ts, src/components/PairPage/PairForm/index.tsx, src/components/PairPage/PairForm/interfaces/index.ts, src/components/PairPage/PairStatus/PairPanelButtons/index.tsx, src/components/PairPage/PairStatus/index.styles.ts, src/components/PairPage/PairStatus/index.tsx, src/components/PairPage/index.tsx, src/definitions/constants/commonConfigs.ts, src/definitions/constants/spiConfigs.ts, src/definitions/types/mx51__spi-client-js.d.ts, src/redux/reducers/pairSlice.ts, src/services/interfaces/index.ts, src/services/spiService.ts, src/services/tests/spiService.test.ts, src/utils/common/pair/pairFormHelpers.ts, src/utils/common/pair/pairStatusHelpers.ts, src/utils/common/spi/common.ts, src/utils/common/spi/eventTarget.ts, src/utils/validators/pairFormValidators.ts
* Add SPI service initial setup (with unit tests)
* Update a few pair screen ui tweaks
=> Add spi service initial setup and updated few pair screen ui tweaks

.gitignore, azure-pipelines.yml, package-lock.json, package.json
* Added pipeline `azure-pipelines.yml` YAML file
=> Add pipeline setup (build stage) for codebase

package.json, src/redux/reducers/TerminalSlice/interfaces/index.ts, src/redux/reducers/TerminalSlice/terminalsSlice.test.ts, src/redux/reducers/TerminalSlice/terminalsSlice.ts
- Added terminalSlice
- Added test case for terminalSlice
=> Add terminalSlice

src/redux/reducers/PairFormSlice/PairFormSelectors.test.ts
fixed the issue of products typing mismatch cause pipeline build failure
=> fixed products typing issue cause unit tests error

src/components/CashoutPage/__snapshots__/index.test.tsx.snap, src/components/FlowPanel/PairFlow/index.test.tsx, src/components/OrderConfirmation/index.tsx, src/components/OrderLineItem/__snapshots__/index.test.tsx.snap, src/components/OrderLineItem/index.styles.ts, src/components/OrderLineItem/index.tsx, src/components/OrderLineItem/interfaces/index.tsx, src/components/PaymentSummary/__snapshots__/index.test.tsx.snap, src/components/PaymentSummary/index.style.ts, src/components/PaymentSummary/index.test.tsx, src/components/PaymentSummary/index.tsx, src/components/PurchasePage/Order/index.tsx, src/components/RefundPage/__snapshots__/index.test.tsx.snap, src/components/RefundPage/index.tsx, src/components/TransactionProgressModal/__snapshots__/index.test.tsx.snap, src/components/TransactionProgressModal/index.styles.ts, src/components/TransactionProgressModal/index.test.tsx, src/components/TransactionProgressModal/index.tsx, src/definitions/constants/commonConfigs.ts, src/definitions/constants/menuItemsConfigs.tsx, src/definitions/constants/routerConfigs.ts, src/redux/reducers/TerminalSlice/terminalsSliceSelectors.ts, src/router/index.test.tsx, src/services/spiService/index.test.ts, src/services/spiService/index.ts, src/utils/common/purchase/purchaseHelper.ts, src/utils/tests/common.tsx
* added Refund page UI + logics + unit tests
* added some new test cases for few components, such as `<PaymentSummary/>`
* renamed certain test cases by adding keyword 'should'
* updated transaction type constants values across the codebase
=> Add refund page and logics

src/definitions/constants/spiConfigs.ts
* updated version to 2.9.1 for `SetPosInfo` function
=> updated version to 2.9.1 for SetPosInfo function

package-lock.json
* bundle up security vulnerabilities packages as one commit
=> bundle up security vulnerabilities packages as one commit

package-lock.json, package.json
* updated SPI library version to 2.9.2 (Latest so far)
=> updated SPI version to 2.9.2

package-lock.json, package.json
* update burger pos spi version to 2.9.2
=> update burger pos spi version to 2.9.2

package-lock.json, src/components/OrderConfirmation/index.test.tsx, src/components/OrderConfirmation/index.tsx, src/components/PurchasePage/Order/index.tsx, src/components/PurchasePage/ProductList/index.test.tsx, src/components/PurchasePage/ProductList/index.tsx, src/components/TransactionProgressModal/index.styles.ts, src/components/TransactionProgressModal/index.tsx, src/redux/reducers/ProductSlice/productSlice.ts
* fixed the issue of keypad and production selection amount mismatched issue
* added related unit tests (Keep unit test rate above 80%)
* fixed the retry button styling issue
=> MXAINT-144: bugfix for switch between keypad and product selection amount

src/definitions/constants/spiConfigs.ts
* updated pos version for spi library
=> updated POS version for spi library

.eslintrc.json, src/services/spiService/index.ts
* fix payment provider show as undefined in terminal details page
=> INTG-161: fix payment provider show as undefined in terminal details page

src/components/OrderConfirmation/index.test.tsx, src/components/OrderConfirmation/index.tsx, src/components/PairPage/PairStatus/PairPanelButtons/index.test.tsx, src/components/PaymentSummary/index.tsx, src/components/PurchaseFlow/index.tsx, src/redux/reducers/TerminalSlice/interfaces/index.ts, src/redux/reducers/TerminalSlice/terminalsSlice.test.ts, src/redux/reducers/TerminalSlice/terminalsSliceSelectors.test.ts, src/redux/reducers/TerminalSlice/terminalsSliceSelectors.ts, src/utils/common/spi/common.test.ts, src/utils/common/spi/common.ts, src/utils/tests/common.tsx, src/utils/validators/pairFormValidators.test.ts, src/utils/validators/pairFormValidators.ts
* fixed issue of shown wrong amount values in `/order-finished` page
* fixed wrong total transaction amount value in developer panel
* added unit tests including: bugfix amount issue + form field validations + component missed unit tests
* disabled moto button when tip amount is larger than 0
=> INTG-163: Bugfix/display response amount values in order finished page

package.json, public/index.html
=> [INTG-226] updated project page title

package-lock.json, src/components/CashoutPage/__snapshots__/index.test.tsx.snap, src/components/FleetSettingsPage/__snapshots__/index.test.tsx.snap, src/components/Navbar/NavbarHeader/index.tsx, src/components/Navbar/index.test.tsx, src/components/Navbar/index.tsx, src/components/NotFoundPage/__snapshots__/index.test.tsx.snap, src/components/PayAtTablePage/__snapshots__/index.test.tsx.snap, src/components/PayNow/__snapshots__/index.test.tsx.snap, src/components/PreAuthPage/__snapshots__/index.test.tsx.snap, src/components/PurchasePage/__snapshots__/index.test.tsx.snap, src/components/RefundPage/__snapshots__/index.test.tsx.snap, src/components/TerminalsPage/TerminalDetails/__snapshots__/index.test.tsx.snap, src/components/TerminalsPage/__snapshots__/index.test.tsx.snap, src/components/Theme/__snapshots__/index.test.tsx.snap, src/utils/common/spi/common.test.ts, src/utils/common/spi/common.ts
* display developer mode button on related screens
* updated unit tests (ensure test coverage is 80% above)
=> display developer mode button on related screens

src/services/spiService/index.ts
* hidden developer mode toggle when terminal is unpaired
=> hidden developer mode toggle when terminal is unpaired

src/components/OrderConfirmation/index.tsx, src/components/TransactionProgressModal/index.styles.ts, src/components/TransactionProgressModal/index.test.tsx, src/components/TransactionProgressModal/index.tsx, src/components/TransactionProgressModal/interfaces/index.ts
[Ticket](https://mx51.atlassian.net/browse/INTG-248)
Added transaction description to the modal for declined transactions.
=> INTG-248 added description to modal

CHANGELOG.MD, package.json
INTG-506 Create a change log file for the EspressoPOS project
=> Feature/INTG-506 Create a change log file for the EspressoPOS project

.eslintrc.json, package.json, src/components/Navbar/DrawerList/DrawerList.tsx, src/services/spiService/index.ts, src/utils/constants.ts
@jwsandeman  Gopi has a different way of getting the version in package.json. I think your way is cleaner, so I made this PR to keep your approach, and refactor a little bit.
=> INTG-544 INTG-549 Getting the version of package.json the same way.

CHANGELOG.MD, src/definitions/constants/menuItemsConfigs.tsx, src/router/index.tsx
Update changelog
Hide preauth feature.
=> Update changelog and hide preauth

src/components/Navbar/DrawerList/DrawerList.tsx, src/components/Navbar/Navbar.test.tsx, src/components/PairPage/PairPage.tsx, src/components/PairPage/index.styles.ts, src/components/PurchasePage/__snapshots__/PurchasePage.test.tsx.snap, src/components/TerminalsPage/TerminalList/TerminalList.tsx, src/components/TerminalsPage/TerminalList/__snapshots__/TerminalList.test.tsx.snap, src/components/TerminalsPage/TerminalsPage.test.tsx, src/components/TerminalsPage/TerminalsPage.tsx, src/components/TerminalsPage/__snapshots__/TerminalsPage.test.tsx.snap, src/definitions/constants/menuItemsConfigs.tsx, src/definitions/constants/routerConfigs.ts
https://mx51.atlassian.net/browse/INTG-651
=> [INTG-651] Store terminal profiles

src/components/CashoutPage/__snapshots__/CashoutPage.test.tsx.snap, src/components/NoTerminalPage/NoTerminalPage.tsx, src/components/OrderConfirmation/OrderConfirmation.tsx, src/components/PairPage/PairForm/PairConfiguration/PairConfiguration.tsx, src/components/PayAtTablePage/PayAtTablePage.tsx, src/components/PayAtTablePage/__snapshots__/PayAtTablePage.test.tsx.snap, src/components/PayNow/__snapshots__/PayNow.test.tsx.snap, src/components/PreAuthPage/__snapshots__/PreAuthPage.test.tsx.snap, src/components/PurchasePage/__snapshots__/PurchasePage.test.tsx.snap, src/components/RefundPage/__snapshots__/RefundPage.test.tsx.snap, src/components/TerminalsPage/TerminalsPage.tsx, src/redux/reducers/TerminalSlice/terminalsSliceSelectors.test.ts, src/redux/reducers/TerminalSlice/terminalsSliceSelectors.ts
https://mx51.atlassian.net/browse/INTG-793
=> [INTG-793] No terminal notifications

CHANGELOG.MD, package-lock.json, package.json, src/components/SplitPage/InitalSplitPanel/InitialSplitPanel.tsx, src/components/SplitPage/SplitAmountPanel/SplitAmountPanel.styles.ts, src/components/SplitPage/SplitAmountPanel/SplitAmountPanel.tsx, src/components/SplitPage/SplitConfirmationPanel/SplitConfirmationPanel.tsx, src/components/SplitPage/SplitNumberPanel/SplitNumberPanel.tsx, src/components/SplitPage/SplitPage.tsx, src/components/SplitPage/SplitReceiptPanel/SplitReceiptPanel.styles.ts, src/components/SplitPage/SplitReceiptPanel/SplitReceiptPanel.tsx, src/components/SplitPage/SummaryPanel/SummaryPanel.tsx
https://mx51.atlassian.net/browse/INTG-784
=> [INTG-784] Split billing by amount

src/components/TransactionProgressModal/TransactionProgressModal.tsx
Fix the missing icon is transaction progress modal dialog.
=> [INTG-803] Fix missing icon

src/components/SplitPage/InitalSplitPanel/InitialSplitPanel.styles.ts, src/components/SplitPage/InitalSplitPanel/InitialSplitPanel.test.tsx, src/components/SplitPage/InitalSplitPanel/InitialSplitPanel.tsx, src/components/SplitPage/InitalSplitPanel/__snapshots__/InitialSplitPanel.test.tsx.snap, src/components/SplitPage/SplitAmountPanel/SplitAmountPanel.tsx, src/components/SplitPage/SplitConfirmationPanel/SplitConfirmationPanel.tsx, src/components/SplitPage/SplitReceiptPanel/SplitReceiptPanel.tsx
https://mx51.atlassian.net/browse/INTG-784
1. Change the default amount of first split to 0
2. Fix a bug that split amount does not change when subtotal amount changes
3. Disable next button and show an error message when subtotal amount is 0
=> [INTG-784] Bug fix and design changes

CHANGELOG.MD, package-lock.json, package.json
https://mx51.atlassian.net/browse/INTG-933?atlOrigin=eyJpIjoiNWYyNGE3MjRkMGQ4NGY2YTk5ZTQ1M2Q4NmNhNzQ5ODIiLCJwIjoiaiJ9
=> chore: bump spi version

azure-pipelines.yml
since the new esporesspos bucket will be in a different account
=> Splitting the role for prod and nonprod, 

.gitignore, src/components/SpiCloudPairingNewPage/SpiCloudPairingNewPage.tsx, src/components/SpiCloudPairingNewPage/index.styles.ts, src/components/SpiCloudPairingNewPage/index.tsx, src/components/SpiCloudPairingPage/SpiCloudPairingPage.tsx, src/components/SpiCloudPairingPage/index.styles.ts, src/components/SpiCloudPairingPage/index.tsx, src/components/SpiCloudSettingsPage/SpiCloudSettingsPage.tsx, src/components/SpiCloudSettingsPage/index.styles.ts, src/components/SpiCloudSettingsPage/index.tsx, src/definitions/constants/routerConfigs.ts, src/redux/reducers/PairFormSlice/PairFormSelectors.test.ts, src/redux/reducers/PairingSlice/interfaces/index.ts, src/redux/reducers/PairingSlice/pairingSelectors.ts, src/redux/reducers/PairingSlice/pairingSlice.ts, src/redux/reducers/SpiCloudSettingsSlice/interfaces/index.ts, src/redux/reducers/SpiCloudSettingsSlice/spiCloudSettingsSelectors.ts, src/redux/reducers/SpiCloudSettingsSlice/spiCloudSettingsSlice.ts, src/redux/reducers/TerminalSlice/terminalsSliceSelectors.test.ts, src/redux/store.ts, src/router/index.tsx
https://mx51.atlassian.net/browse/INTG-996?atlOrigin=eyJpIjoiY2UxMmQ4NTY4NTg2NDNlNmE2OGFkMTFlYTZhMmUzOGUiLCJwIjoiaiJ9
Just for internal testing so no tests, basic ui etc. Will not merge this into main. If wanting to test hit me up for an API key to replace and also I can provide a MXA build with spi cloud pairing functionality.
=> [INTG-996] add: pairing demo

CHANGELOG.MD, package-lock.json, package.json, src/redux/reducers/PairingSlice/pairingSlice.ts
=> [INTG-1037] fix: remove test pairing
